### PR TITLE
added lammps, changed order in the application notes section

### PR DESCRIPTION
**Pull request by arkdavy**
New LAMMPS page has a link to github repository (https://github.com/arkdavy/LAMMPS) with EB installation scrips and performance plots.

### CODE REVIEW

**Comment by dquigley-warwick** [comment]
Thanks for this Arkadiy - I'll take a read through when I can this week and let you know if anything isn't clear.

**Comment by dquigley-warwick** [comment]
Hi Arkadiy,

Some queries/suggestions from me.

1. In your job script examples you're invoking lammps with srun via

```bash
srun `which lmp`
```

rather than just
```bash
srun lmp
```
is there a reason for that I've missed?

2. The build instructions suggest that only building against CUDA is suggested. Do we maybe want two sections here, one for CPU-only building and one for GPU building?

3.  For the MPI-only timings, what is the number of MPI tasks and how was this chosen? From the plots you link to it seems that 64 MPI tasks per node would be a sensible choice since there's little extra speedup beyond that and users would get better throughput by running two 64-task calculations per node instead? I'd normally consider anything less than 75% parallel efficiency to be wasteful, and it looks like you're below that if quoting numbers for 128 cores?

[Might be worth plotting parallel speedup T(1)/T(N) or efficiency T(1)/(N*T(N)) instead of just T(N) to highlight that.]

It's worth stating here explicitly that when quoting OpenMP+MPI numbers that you keep the number of tasks x threads-per-task constant? Did you try 2 threads per task or just 4, 8 and 16? I seem to remember 2 being optimal on other systems.

4. Similar query for the GPU numbers. Did you keep a fixed number of CPUs per GPU for these tests and were those all used by MPI tasks?

Other than the above queries there's a few English things I should correct. I'll see if I can send you a patch for that so you can update the PR.

David

**Comment by arkdavy** [comment]
Hi David,

Thank you for your review! I have made some changes to the data according to your comments.

It looks better, but there was a point where my calculations were slow. I have placed here a hypothesis that it is due to inefficient OpenMP threads distribution, which is solved by cpu-binding, but I could not reproduce that behaviour anymore (i.e., even submitting the original scripts in a "non-high-throughput" fashion).

1. There was no really a reason for `which lmp` in the Sulis/modules context, just plugging the full path everywhere. Removed in the current version

2. I was assuming that we won't install the LAMMPS+`GPU` package on Sulis, but will encourage building this at home/ if needed, for which the instruction is written. But indeed, if someone would need a package other than the `GPU`, the CPU instructions are useful. I have added the instructions allowing for "most" packages.

3.  The MPI-only computations were done with 1core per MPI process.
`.. use two 64-task calculations per node instead..`
the conclusion can be different depending on the system size, type of forces, what is computed, etc... I have reflected this in the `Performance` section.
Then, I think we can not quote 64-core jobs because of interference with other jobs on the same node, and there will be more randomness in the data, but I have added the caution " Our advise, however, is to use less cores in this situation (64 or less)..."
`stating here explicitly that when quoting OpenMP+MPI numbers that ...`. I have added the info in my LAMMPS repository how the number of MPI tasks can be deduced from the plots (where "number of cores = number of tasks x threads-per-task". I, technically, was only changing the number of tasks to generate the data, keeping threads-per-task fixed)
I have also updated the data with 1, 2,4,8 OMP_NUM_THREADS and 2 indeed gives the best performance for LAMMPS+LJ+50000 particles

5.  `..Similar query for the GPU numbers. Did you keep a fixed number of CPUs per GPU for these tests and were those all used by MPI tasks?..`.
Oh, I have added this information from PR to my LAMMPS' GitHub page. It was "1xMPI-tasks on 1xCPU per GPU". Other schemes were slowing down the calculations (i.e., using more than one thread-per-task or tasks-per-GPU).

> Other than the above queries there's a few English things I should correct. I'll see if I can send you a patch for that so you can update the PR.

I did my best to fix it! I will appreciate your help. By the way, you should be able to edit my branch directly, I will have to enable it though. Tell me if you don't have that access.

Best,
Arkadiy

**Comment by dquigley-warwick** [comment]
Hi Arkadiy,

Just working through this. I'll see if I can push my modified version to your branch. 

I notice that the lammps modules this refers to don't seem to be available yet? I guess we need @dithwick to deploy those?

**Comment by arkdavy** [comment]
Yes, we will ask Dugan at some point (before merging). I am now trying to submit my easyconfigs to easybuild repo. Maybe we could deploy after my configs pass the EasyBuild tests? It also gives an easier set-up with an option of pulling configs from my PR's at EasyBuild repo. But it depends on how much time it should take though. Regarding merging your changes to this PR, I have tried to find a button that allows it but did not succeed. Hope it is allowed by default

**Comment by dquigley-warwick** [comment]
Still quite surprised that multiple MPI tasks per GPU was slowing that single task but maybe my experience with LAMMPS is out of date. I'll have a play once we've deployed the module.

I *think* I've just successfully pushed some edits to your branch.

**Comment by dquigley-warwick** [comment]
Happy to merge this into the docs but we should probably deploy the modules first. We'll likely want to revisit it if LAMMPS users can provide some additional benchmarks that might modify the conclusions, but we obviously can't test every single use case.

**Comment by arkdavy** [comment]
Thanks a lot! Yes, let's wait until it passes the Easybuild Tests (I am learning how to do the EB pull requests), I should have done it earlier, since some new easyconfings which LAMMPS depends on are already available in the EB development branch in, sometimes, a different form. It should have no effect on running LAMMPS, but it makes the deployment cleaner.

**Pull request merged**
